version: '2'

networks:
  elk:
    driver: bridge


services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      LOGSPOUT: ignore
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.0
    container_name: elk-logstash
    environment:
      TZ: Europe/Paris
      LOGSPOUT: ignore
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    environment:
      LOGSPOUT: ignore
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - elk

  logspout:
    build:
        context: ./logspout
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    environment:
        ROUTE_URIS: "logstash://elk-logstash.elk_elk:5000"
    depends_on:
        - logstash
    restart: always
    networks:
      - elk
